name: sentry
version: 1.0.0
description: A pure Dart Sentry.io client.
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: https://github.com/flutter/sentry

environment:
  sdk: 1.24.3

dependencies:
  app_intelligence:
    hosted:
      name: app_intelligence
      url: https://pub.workiva.org
    version: ^2.19.0
  meta: ">=1.0.0 <2.0.0"
  stack_trace: ">=1.0.0 <2.0.0"
  usage: ">=3.0.0 <4.0.0"
  webdriver: ^1.2.3
  w_transport: ^3.2.5

dev_dependencies:
  args: ">=0.13.0 <2.0.0"
  dart_dev: ^1.9.2
  dart_style: ^1.0.9+1
  dependency_validator: ^1.1.2
  logging: '>=0.9.3 <0.12.0'
  over_react_test: ^1.4.0
  platform_detect: ^1.3.3
  test: ^0.12.32+1
  yaml: ">=2.1.0 <3.0.0"
  mockito: ">=2.0.0 <3.0.0"

transformers:
- test/pub_serve:
    $include: test/**_test.dart
- $dart2js:
    sourceMaps: true
